repos:
  - repo: https://github.com/srstevenson/nb-clean
    rev: 4.0.1
    hooks:
      - id: nb-clean
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
     - id: nbqa-black
       additional_dependencies: [black==26.3.1]
     - id: nbqa-pyupgrade
       additional_dependencies: [pyupgrade==3.21.2]
     - id: nbqa-pylint
       additional_dependencies: [pylint==4.0.5]
       args: ["--disable=missing-module-docstring,import-error,wrong-import-position,wrong-import-order,ungrouped-imports"]
