name: spellcheck

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches: [ main ]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: pip install nbconvert ipykernel
      - run: python -m nbconvert --to markdown *.ipynb
      - uses: rojopolis/spellcheck-github-actions@0.60.0
        with:
          spell_checker: hunspell
